<?php
require_once __DIR__ . "/../../../core/config.php";
require_once PROJECT_PATH . "/j_conn.php";
require_once PROJECT_PATH . "/auth.php";
require_once PROJECT_PATH . "/access_check.php";
require_once PROJECT_PATH . "/functions.php";

// Check if user's college/program is hidden
checkUserAccess($con);
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BRIDGE</title>
        <!-- Correct jQuery CDN -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <!-- Correct DataTables JS CDN -->
        <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
        <!-- Correct DataTables CSS CDN 
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="modules/generate_report/css/generate_report.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.js"></script>
        <!-- Bootstrap 5.3.3 CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
        <link rel="shortcut icon" href="Pictures/favicon.ico" type="image/x-icon">
    </head>
    <body>
        <header class="top-header">
            <a href="home">
                <img src="Pictures/white_logo.png" alt="MCU Logo" class="logo img-fluid">
            </a>
        </header>

        <h2 class="headings">Generate Report</h2>

        <div class="button-container">
            <a href="generate-report-filter" class="control return-btn back-page" title="Return to Filter Students">
                <i class="bi bi-arrow-return-left"></i>Return
            </a>
            <button onclick="openStatisticalToolModal()" class="primary-button select-tool-btn" title="Compare Students">
                <i class="bi bi-bar-chart-line"></i>Select Statistical Tool</button>
            <button id="printBtn" class="primary-button print-btn" title="Print Report">
                <i class="bi bi-printer"></i> Print
            </button>
            <div class="export-dropdown">
                <button class="primary-button export-btn" id="exportDropdownBtn" type="button">
                    <i class="bi bi-download"></i> Export
                    <i class="bi bi-caret-down"></i>
                </button>
                <div class="export-menu" id="exportMenu">
                    <button class="export-option" id="exportPdfDropdownBtn">
                        <i class="bi bi-file-earmark-pdf"></i> Export as PDF
                    </button>
                    <button class="export-option" id="exportWordDropdownBtn">
                    <i class="bi bi-file-earmark-word"></i> Export as Word
                    </button>
                </div>
            </div>
        </div>

        <!-- Scroll Notification Banner -->
        <div id="scrollNotification" class="scroll-notification">
            <i class="bi bi-arrow-left-right icon"></i>
            <span>Swipe right or scroll horizontally to view full report</span>
            <button class="close-btn" onclick="hideScrollNotification()">&times;</button>
        </div>

        <div class="report-wrapper hidden" id="reportWrapper">
            <div id="report">
                <header class="report-header">
                    <div>
                    <div class="title">Manila Central University Statistical Report</div>
                        <div class="meta">BRIDGE Generated: <span id="generatedAt"></span></div>
                    </div>
                    <div class="meta">Generated by: 
                        <?php 
                            if (isset($_SESSION['firstname'], $_SESSION['lastname'])) {
                                echo $_SESSION['firstname'] . ' ' . $_SESSION['lastname'];
                            } else {
                                echo 'User'; 
                            }
                        ?>
                    </div>
                </header>
                <section class="section">
        
                    <!-- Report Summary -->
                    <div id="reportSummary"></div>
                    
                    <div id="generatedReport" class="hidden generated-report">
                        <h2>Generated Report:</h2>
                        <div id="generatedReportSummary" class="report-summary"></div>
                        <div id="reportChart" class="chart"></div>
                    </div>
                </section>

                <footer style="font-size:11px;color:#718096">
                    Note: PDF and Print are both locked to 1366px laptop layout. Table and chart auto-fit the Letter page.
                </footer>
            </div>
        </div>

        <!-- Statistical Tool Selection Modal -->
        <div id="statisticalToolModal" class="modal">
            <div class="modal-content">
                <h2 class="modal-header">Statistical Analysis Configuration</h2>
                <div class="form-container">

                    <div id="fieldSelectionDescriptive">
                        <!-- Field 0 Selection -->
                        <div class="field-group">
                            <h4>Variable</h4>
                            <div class="form-group">
                                <label for="field0Category">Category:</label>
                                <select id="field0Category" onchange="handleField0CategoryChange()">
                                    <option value="" disabled>Select</option>
                                    <option value="studentInfo">Student Information</option>
                                    <option value="academicProfile">Academic Profile</option>
                                    <option value="programMetrics">Program Metrics</option>
                                </select>
                            </div>

                            <!-- Student Info Fields -->
                            <div id="field0StudentInfo" class="form-group hidden">
                                <label for="field0StudentField">Field:</label>
                                <select id="field0StudentField" onchange="handleField0StudentInfoMetricChange()">
                                    <option value="" disabled>Select</option>
                                    <option value="age">Age</option>
                                    <option value="socioeconomicStatus">Socioeconomic Status</option>
                                </select>
                            </div>

                            <!-- Academic Profile Fields -->
                            <div id="field0AcademicProfile" class="form-group hidden">
                                <label for="field0AcademicMetric">Metric:</label>
                                <select id="field0AcademicMetric" onchange="handleField0AcademicMetricChange()">
                                    <option value="" disabled>Select</option>
                                    <option value="GWA">GWA</option>
                                    <option value="BoardGrades">Grades in Board Subjects</option>
                                    <option value="Retakes">Back Subjects/Retakes</option>
                                    <option value="PerformanceRating">Performance Rating</option>
                                    <option value="SimExam">Simulation Exam Results</option>
                                    <option value="Attendance">Attendance in Review Classes</option>
                                    <option value="Recognition">Academic Recognition</option>
                                </select>
                            </div>

                            <!-- Program Metrics Fields -->
                            <div id="field0ProgramMetrics" class="form-group hidden">
                                <label for="field0ProgramMetric">Metric:</label>
                                <select id="field0ProgramMetric" onchange="handleField0ProgramMetricChange()">
                                    <option value="" disabled>Select</option>
                                    <option value="MockScores">Mock Board Scores</option>
                                    <option value="TakeAttempt">Number of Exam Attempts</option>
                                </select>
                            </div>

                            <!-- Dynamic sub-combobox -->
                            <div id="subMetricGroup" class="form-group hidden">
                                <label for="subMetricSelect" id="subMetricLabel"></label>
                                <select name="subMetricSelect" id="subMetricSelect" onchange="handleField0SubMetricChange()">
                                    <option value="" disabled>Select</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-buttons">                  
                    <button onclick="closeStatisticalToolModal()" class="btn-clear">Cancel</button>
                    <button onclick="generateReport()">Generate Report</button>
                </div>
            </div>
        </div>

        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
        <script>
    
            function delay(ms){ return new Promise(res=>setTimeout(res,ms)); }

            // Unified snapshot function (from test.html)
            async function getSnapshot(scale = 2) {
                try { 
                    if (window.myChart && window.myChart.resize) window.myChart.resize(); 
                } catch (e) {}
                await delay(300); // allow chart to finish rendering
                // ensure report width is the intended desktop width during snapshot
                const report = document.getElementById('report');
                const prevWidth = report.style.width;
                report.style.width = getComputedStyle(report).width || report.style.width || (1366 + "px");
                const canvas = await html2canvas(report, {
                    scale: scale,
                    useCORS: true,
                    allowTaint: true,
                    logging: false,
                    windowWidth: 1366,
                    width: 1366
                });
                report.style.width = prevWidth; // restore
                return canvas;
            }

            // Helper to resize canvas to fit Word printable area with maximum quality
            function resizeCanvasForWord(originalCanvas) {
                const printableWidthPx = 624; // 6.5in * 96dpi (adjusted for Word's default 1in margins; tighter fit)
                const originalWidth = originalCanvas.width;
                const originalHeight = originalCanvas.height;
                const scaleFactor = printableWidthPx / originalWidth;
                const newHeight = Math.floor(originalHeight * scaleFactor);

                // Strategy: Use multiple intermediate steps for better quality
                // Step 1: Scale to a very high resolution first
                const highResFactor = 4; // Scale to 4x the target size
                const highResWidth = printableWidthPx * highResFactor;
                const highResHeight = newHeight * highResFactor;
                
                const highResCanvas = document.createElement('canvas');
                highResCanvas.width = highResWidth;
                highResCanvas.height = highResHeight;
                const highResCtx = highResCanvas.getContext('2d');
                
                highResCtx.imageSmoothingEnabled = true;
                highResCtx.imageSmoothingQuality = 'high';
                highResCtx.drawImage(originalCanvas, 0, 0, highResWidth, highResHeight);
                
                // Step 2: Scale down to 2x target size
                const midResWidth = printableWidthPx * 2;
                const midResHeight = newHeight * 2;
                
                const midResCanvas = document.createElement('canvas');
                midResCanvas.width = midResWidth;
                midResCanvas.height = midResHeight;
                const midResCtx = midResCanvas.getContext('2d');
                
                midResCtx.imageSmoothingEnabled = true;
                midResCtx.imageSmoothingQuality = 'high';
                midResCtx.drawImage(highResCanvas, 0, 0, midResWidth, midResHeight);
                
                // Step 3: Final scale to target size
                const finalCanvas = document.createElement('canvas');
                finalCanvas.width = printableWidthPx;
                finalCanvas.height = newHeight;
                const finalCtx = finalCanvas.getContext('2d');
                
                finalCtx.imageSmoothingEnabled = true;
                finalCtx.imageSmoothingQuality = 'high';
                finalCtx.drawImage(midResCanvas, 0, 0, printableWidthPx, newHeight);
                
                return finalCanvas;
            }
                
                // Open modal on page load
                window.addEventListener('load', function() {
                    openStatisticalToolModal();
                });
                
                // Function to show report wrapper and set timestamp when report is generated
                function showReportWrapper() {
                    document.getElementById('reportWrapper').classList.remove('hidden');
                    document.getElementById('generatedAt').textContent = new Date().toLocaleString();
                }

                // Chart.js setup (guard if canvas exists)
                const chartCanvasEl = document.getElementById('chartCanvas');
                if (chartCanvasEl) {
                const ctx = chartCanvasEl.getContext('2d');
                window.myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['A','B','C','D','E','F','G','H'],
                    datasets: [{
                    label: 'Score',
                    data: [85,90,78,65,92,71,71,71],
                    backgroundColor: ['#4caf50','#2196f3','#ffb300','#f44336','#9c27b0','#3f51b5','#e91e63','#607d8b']
                    }]
                },
                options: {
                    maintainAspectRatio: false,
                    responsive: true,
                    plugins: { legend: { display: false } },
                    scales: { y: { beginAtZero:true, max:100 } }
                }
                });
                }

                /* --------------------------
                   PRINT (no about:blank tab)
                   - create a hidden iframe
                   - write a printable HTML with the image sized to the page width
                   - call iframe.contentWindow.print()
                   - remove iframe
                   -------------------------- */
                document.getElementById('printBtn').addEventListener('click', async () => {
                    try {
                        const canvas = await getSnapshot();
                        const imgData = canvas.toDataURL("image/png");

                        // Create hidden iframe
                        const iframe = document.createElement("iframe");
                        iframe.style.position = "fixed";
                        iframe.style.right = "0";
                        iframe.style.bottom = "0";
                        iframe.style.width = "0";
                        iframe.style.height = "0";
                        iframe.style.border = "0";
                        iframe.setAttribute("aria-hidden", "true");
                        document.body.appendChild(iframe);

                        const doc = iframe.contentWindow.document;
                        // Build printable HTML — use page wrapper that respects a typical Letter page with 0.5in margins.
                        doc.open();
                        doc.write(`
                            <html>
                              <head>
                                <title>Print</title>
                                <style>
                                  @page { size: Letter portrait; margin: 0.5in; }
                                  html,body { margin:0; padding:0; height:100%; }
                                  .page { width:100%; box-sizing:border-box; padding:0; }
                                  img { display:block; max-width:100%; height:auto; width:100%; }
                                </style>
                              </head>
                              <body>
                                <div class="page"><img src="${imgData}" alt="report"/></div>
                              </body>
                            </html>
                        `);
                        doc.close();

                        // wait for image to load inside iframe before printing
                        const printPromise = new Promise((resolve) => {
                            const img = doc.querySelector("img");
                            if (!img) { resolve(); return; }
                            if (img.complete) { resolve(); return; }
                            img.onload = () => resolve();
                            img.onerror = () => resolve(); // on error still proceed
                        });

                        await printPromise;

                        // call print on the iframe window — avoids opening a blank tab
                        iframe.contentWindow.focus();
                        iframe.contentWindow.print();

                        // Give the browser a moment, then remove the iframe to clean up
                        setTimeout(() => {
                            try { document.body.removeChild(iframe); } catch (e) {}
                        }, 500);
                    } catch (err) {
                        console.error("Print snapshot error:", err);
                        alert("Print failed — check console.");
                    }
                });

            // Also stabilize onbeforeprint: match test.html (just ensure chart is laid out)
            window.onbeforeprint = async () => {
            try {
                if (window.myChart && window.myChart.resize) window.myChart.resize();
                await delay(300);
            } catch (e) {
                console.error('beforeprint error:', e);
            }
            };

            window.onafterprint = () => {
            try { if (window.myChart && window.myChart.resize) window.myChart.resize(); } catch (e) {}
            };


                /* --------------------------
                   PDF export (same snapshot)
                   -------------------------- */
                const exportPdfBtn = document.getElementById('exportPdfBtn');
                if (exportPdfBtn) {
                    exportPdfBtn.addEventListener('click', async () => {
                    try {
                        const canvas = await getSnapshot();

                // Letter page size in points (px at 72 dpi) — match test.html (no margins)
                        const imgData = canvas.toDataURL("image/png");
                        const { jsPDF } = window.jspdf;
                        const pdf = new jsPDF({ unit: "pt", format: "letter", orientation: "portrait" });

                        const pageWidth = pdf.internal.pageSize.getWidth();
                        const pageHeight = pdf.internal.pageSize.getHeight();
                        const imgWidth = canvas.width;
                        const imgHeight = canvas.height;

                        // keep small top margin (36pt = 0.5in)
                        const margin = 36;
                        const contentW = pageWidth - margin * 2;
                        const contentH = pageHeight - margin * 2;
                        const scale = Math.min(contentW / imgWidth, contentH / imgHeight);

                        const w = imgWidth * scale;
                        const h = imgHeight * scale;
                        const x = margin + (contentW - w) / 2;
                        const y = margin;

                        pdf.addImage(imgData, "PNG", x, y, w, h);
                        pdf.save("report.pdf");
                    } catch (err) {
                        console.error("PDF export error:", err);
                        alert("Export to PDF failed — check console.");
                    }
                    });
                }

                /* --------------------------
                   WORD export (fit image into a Word page, no cropping)
                   - Pre-resize the canvas to exactly fit the printable width (6.5in at 96dpi = 624px for Word's default 1in margins)
                   - This provides a tighter fit ("just a few more" pixels shaved off) to ensure no overflow in Word's rendering
                   - Use CSS width:100% in the container for proportional fit; flex centers it
                   -------------------------- */
                const exportWordBtn = document.getElementById('exportWordBtn');
                if (exportWordBtn) {
                    exportWordBtn.addEventListener('click', async () => {
                    try {
                        const originalCanvas = await getSnapshot(6); // Even higher scale for maximum quality
                        const resizedCanvas = resizeCanvasForWord(originalCanvas);
                        const imgData = resizedCanvas.toDataURL("image/png");

                        // Build an HTML wrapper that approximates an 8.5 x 11 in page with 1in margins (Word default).
                        // Since image is pre-sized to 624px (6.5in), width:100% fits perfectly without scaling issues.
                        const htmlContent = `
<html xmlns:o='urn:schemas-microsoft-com:office:office'
      xmlns:w='urn:schemas-microsoft-com:office:word'
      xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset="utf-8"><title>Report</title>
<meta name="ProgId" content="Word.Document">
<style>
  /* Force Word defaults: 1in margins via padding on page container */
  .word-page {
    width: 8.5in;
    height: 11in;
    box-sizing: border-box;
    padding: 1in; /* Matches Word's default margins — inner area 6.5in wide */
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .word-page img {
    width: 100%; /* Fits exactly to 6.5in inner width */
    height: auto; /* Proportional, no cropping */
    max-width: 6.5in; /* Fallback for any rendering quirks */
  }
  body { margin:0; padding:0; }
  html { margin:0; padding:0; }
  /* Additional Word-specific: Ensure no extra spacing */
  p, div { margin: 0; padding: 0; }
</style>
</head>
<body>
  <div class="word-page">
    <img src="${imgData}" alt="report" />
  </div>
</body>
</html>`;

                        // Create a blob and trigger download as .doc
                        const blob = new Blob(['\ufeff', htmlContent], { type: 'application/msword' });
                        const url = URL.createObjectURL(blob);
                        const a = document.createElement("a");
                        a.href = url;
                        a.download = "report.doc";
                        document.body.appendChild(a);
                        a.click();
                        document.body.removeChild(a);
                        URL.revokeObjectURL(url);
                    } catch (err) {
                        console.error("Word export error:", err);
                        alert("Export to Word failed — check console.");
                    }
                    });
                }

                // Add event listeners for dropdown export buttons
                const exportPdfDropdownBtn = document.getElementById('exportPdfDropdownBtn');
                if (exportPdfDropdownBtn) {
                    exportPdfDropdownBtn.addEventListener('click', async () => {
                    try {
                        const canvas = await getSnapshot();

                // Letter page size in points (px at 72 dpi) — match test.html (no margins)
                        const imgData = canvas.toDataURL("image/png");
                        const { jsPDF } = window.jspdf;
                        const pdf = new jsPDF({ unit: "pt", format: "letter", orientation: "portrait" });

                        const pageWidth = pdf.internal.pageSize.getWidth();
                        const pageHeight = pdf.internal.pageSize.getHeight();
                        const imgWidth = canvas.width;
                        const imgHeight = canvas.height;

                        // keep small top margin (36pt = 0.5in)
                        const margin = 36;
                        const contentW = pageWidth - margin * 2;
                        const contentH = pageHeight - margin * 2;
                        const scale = Math.min(contentW / imgWidth, contentH / imgHeight);

                        const w = imgWidth * scale;
                        const h = imgHeight * scale;
                        const x = margin + (contentW - w) / 2;
                        const y = margin;

                        pdf.addImage(imgData, "PNG", x, y, w, h);
                        pdf.save("report.pdf");
                    } catch (err) {
                        console.error("PDF export error:", err);
                        alert("Export to PDF failed — check console.");
                    }
                    });
                }

                const exportWordDropdownBtn = document.getElementById('exportWordDropdownBtn');
                if (exportWordDropdownBtn) {
                    exportWordDropdownBtn.addEventListener('click', async () => {
                    try {
                        const originalCanvas = await getSnapshot(6); // Even higher scale for maximum quality
                        const resizedCanvas = resizeCanvasForWord(originalCanvas);
                        const imgData = resizedCanvas.toDataURL("image/png");

                        // Build an HTML wrapper that approximates an 8.5 x 11 in page with 1in margins (Word default).
                        // Since image is pre-sized to 624px (6.5in), width:100% fits perfectly without scaling issues.
                        const htmlContent = `
<html xmlns:o='urn:schemas-microsoft-com:office:office'
      xmlns:w='urn:schemas-microsoft-com:office:word'
      xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset="utf-8"><title>Report</title>
<meta name="ProgId" content="Word.Document">
<style>
  /* Force Word defaults: 1in margins via padding on page container */
  .word-page {
    width: 8.5in;
    height: 11in;
    box-sizing: border-box;
    padding: 1in; /* Matches Word's default margins — inner area 6.5in wide */
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .word-page img {
    width: 100%; /* Fits exactly to 6.5in inner width */
    height: auto; /* Proportional, no cropping */
    max-width: 6.5in; /* Fallback for any rendering quirks */
  }
  body { margin:0; padding:0; }
  html { margin:0; padding:0; }
  /* Additional Word-specific: Ensure no extra spacing */
  p, div { margin: 0; padding: 0; }
</style>
</head>
<body>
  <div class="word-page">
    <img src="${imgData}" alt="report" />
  </div>
</body>
</html>`;

                        // Create a blob and trigger download as .doc
                        const blob = new Blob(['\ufeff', htmlContent], { type: 'application/msword' });
                        const url = URL.createObjectURL(blob);
                        const a = document.createElement("a");
                        a.href = url;
                        a.download = "report.doc";
                        document.body.appendChild(a);
                        a.click();
                        document.body.removeChild(a);
                        URL.revokeObjectURL(url);
                    } catch (err) {
                        console.error("Word export error:", err);
                        alert("Export to Word failed — check console.");
                    }
                    });
                }

                window.onbeforeprint = () => { try { if (window.myChart && window.myChart.resize) window.myChart.resize(); } catch(e){} };
                window.onafterprint = () => { try { if (window.myChart && window.myChart.resize) window.myChart.resize(); } catch(e){} };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="core/logout_inform.js"></script>
        <script src="core/get_pending_count.js"></script>
        <script src="core/session_warning.js"></script>
        <script src="modules/generate_report/js/generate_report_programs.js">
        </script>
        <script>
            window.userSession = {
            level: <?php echo json_encode($_SESSION['level'] ?? ''); ?>,
            college: <?php echo json_encode($_SESSION['college'] ?? ''); ?>,
            program: <?php echo json_encode($_SESSION['program'] ?? ''); ?>,
            filter_college: <?php echo json_encode($_SESSION['filter_college'] ?? ''); ?>,
            filter_program: <?php echo json_encode($_SESSION['program'] ?? ''); ?>,
            filter_year_batch: <?php echo json_encode($_SESSION['filter_year_batch'] ?? ''); ?>,
            filter_board_batch: <?php echo json_encode($_SESSION['filter_board_batch'] ?? ''); ?>
            };
        document.getElementById("field0Category").value = "";
        document.getElementById("subMetricSelect").value = "";
        document.getElementById("field0StudentField").value = "";
        document.getElementById("field0AcademicMetric").value = "";
        document.getElementById("field0ProgramMetric").value = "";
    </script>
    </body>
</html>